site_name: TT Labs

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            extra:
              docstring_section_style: table
              doctring_style: google
              docstring_options:
                ignore_init_summary: true
                trim_doctest_flags: true

nav:
  - Home: index.md
  - API: api.md

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: amber
  font:
    text: Roboto
    code: Roboto Mono
    features:
      - "liga"          # Enable ligatures
      - "tnum"          # Tabular numbers for code